<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * MYBOOKING CHECKOUT FORM — Field Catalog
 *
 * Defines all fields that can be placed in the checkout form builder.
 *
 * Each entry:
 *   type         : input type rendered on the frontend (text|email|tel|textarea|select|date)
 *   label        : default translatable label
 *   placeholder  : default translatable placeholder (empty string if none)
 *   required     : whether the field is required by default
 *   removable    : false = field is locked in the form and cannot be removed by the admin
 *   maxlength    : max input length (0 = no limit)
 *   has_intl_tel : true = the engine will init intlTelInput on this field (phone prefix + flag)
 *   datepicker   : 'birth' | 'license' | '' — drives Flatpickr config on the frontend
 *   special      : 'delivery_slot' | 'external_driver' | '' — fields managed by the engine at runtime.
 *                  Rendered as special HTML blocks; visibility controlled by the JS engine.
 *   group        : logical grouping for the admin panel UI
 */

/**
 * Returns the checkout field catalog with labels translated to the current admin locale.
 * Uses static memoization — first call happens at admin page render, after the text domain
 * is loaded, so _x() returns the correct translated strings for every subsequent call.
 */
if ( ! function_exists( 'mybooking_checkout_form_fields' ) ) {
  function mybooking_checkout_form_fields() {
    static $fields = null;
    if ( $fields !== null ) {
      return $fields;
    }
    $fields = [

    // ── Customer (core — locked) ────────────────────────────────────────────
    'customer_name' => [
      'type'         => 'text',
      'label'        => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => true,
      'removable'    => false,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'customer',
    ],
    'customer_surname' => [
      'type'         => 'text',
      'label'        => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => true,
      'removable'    => false,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'customer',
    ],
    'customer_email' => [
      'type'         => 'text',
      'label'        => _x( 'E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => true,
      'removable'    => false,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'customer',
    ],

    // ── Customer (optional) ─────────────────────────────────────────────────
    'confirm_customer_email' => [
      'type'         => 'text',
      'label'        => _x( 'Confirm E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Confirm E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'customer',
    ],
    'customer_phone' => [
      'type'         => 'tel',
      'label'        => _x( 'Phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 15,
      'has_intl_tel' => true,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'customer',
    ],
    'customer_mobile_phone' => [
      'type'         => 'tel',
      'label'        => _x( 'Alternative phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Alternative phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 15,
      'has_intl_tel' => true,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'customer',
    ],
    'comments' => [
      'type'         => 'textarea',
      'label'        => _x( 'Comments', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Comments', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 0,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'customer',
    ],

    // ── Address ─────────────────────────────────────────────────────────────
    'street' => [
      'type'         => 'text',
      'label'        => _x( 'Street', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Street', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 60,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'address',
    ],
    'number' => [
      'type'         => 'text',
      'label'        => _x( 'Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'address',
    ],
    'complement' => [
      'type'         => 'text',
      'label'        => _x( 'Complement', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Complement', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 20,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'address',
    ],
    'city' => [
      'type'         => 'text',
      'label'        => _x( 'City', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'City', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 60,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'address',
    ],
    'state' => [
      'type'         => 'text',
      'label'        => _x( 'State', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'State', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 60,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'address',
    ],
    'country' => [
      'type'         => 'text',
      'label'        => _x( 'Country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'address',
    ],
    'zip' => [
      'type'         => 'text',
      'label'        => _x( 'Postal code', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Postal code', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'address',
    ],

    // ── Flight (arrival) ────────────────────────────────────────────────────
    'fligth_airport_origin' => [
      'type'         => 'text',
      'label'        => _x( 'Origin airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Origin airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 100,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_arrival',
    ],
    'flight_company' => [
      'type'         => 'text',
      'label'        => _x( 'Airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 80,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_arrival',
    ],
    'flight_number' => [
      'type'         => 'text',
      'label'        => _x( 'Flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_arrival',
    ],
    'flight_time' => [
      'type'         => 'text',
      'label'        => _x( 'Expected arrival time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'HH:MM',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 5,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_arrival',
    ],

    // ── Flight (departure) ──────────────────────────────────────────────────
    'fligth_airport_destination' => [
      'type'         => 'text',
      'label'        => _x( 'Destination airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Destination airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 100,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_departure',
    ],
    'flight_company_departure' => [
      'type'         => 'text',
      'label'        => _x( 'Return airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Return airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 80,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_departure',
    ],
    'flight_number_departure' => [
      'type'         => 'text',
      'label'        => _x( 'Return flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Return flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_departure',
    ],
    'flight_time_departura' => [
      'type'         => 'text',
      'label'        => _x( 'Expected return time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'HH:MM',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 5,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'flight_departure',
    ],

    // ── Driver ──────────────────────────────────────────────────────────────
    'driver_name' => [
      'type'         => 'text',
      'label'        => _x( 'Driver name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Driver name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'driver',
    ],
    'driver_surname' => [
      'type'         => 'text',
      'label'        => _x( 'Driver surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Driver surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'driver',
    ],
    'driver_document_id' => [
      'type'         => 'text',
      'label'        => _x( 'Driver ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Driver ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'driver',
    ],
    'driver_date_of_birth' => [
      'type'         => 'date',
      'label'        => _x( 'Date of birth', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'birth',
      'special'      => '',
      'group'        => 'driver',
    ],
    'driver_driving_license_number' => [
      'type'         => 'text',
      'label'        => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'driver',
    ],
    'driver_driving_license_date' => [
      'type'         => 'date',
      'label'        => _x( 'License issue date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'license',
      'special'      => '',
      'group'        => 'driver',
    ],
    'driver_driving_license_country' => [
      'type'         => 'text',
      'label'        => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'driver',
    ],
    'driver_driving_license_expiration_date' => [
      'type'         => 'date',
      'label'        => _x( 'License expiry date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'license',
      'special'      => '',
      'group'        => 'driver',
    ],

    // ── Additional driver 1 ─────────────────────────────────────────────────
    'additional_driver_1_name' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 1 — Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],
    'additional_driver_1_surname' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 1 — Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],
    'additional_driver_1_document_id' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 1 — ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],
    'additional_driver_1_date_of_birth' => [
      'type'         => 'date',
      'label'        => _x( 'Additional driver 1 — Date of birth', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'birth',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],
    'additional_driver_1_driving_license_number' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 1 — License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],
    'additional_driver_1_driving_license_date' => [
      'type'         => 'date',
      'label'        => _x( 'Additional driver 1 — License issue date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'license',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],
    'additional_driver_1_driving_license_country' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 1 — License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],
    'additional_driver_1_driving_license_expiration_date' => [
      'type'         => 'date',
      'label'        => _x( 'Additional driver 1 — License expiry', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'license',
      'special'      => '',
      'group'        => 'additional_driver_1',
    ],

    // ── Additional driver 2 ─────────────────────────────────────────────────
    'additional_driver_2_name' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 2 — Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],
    'additional_driver_2_surname' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 2 — Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 40,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],
    'additional_driver_2_document_id' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 2 — ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],
    'additional_driver_2_date_of_birth' => [
      'type'         => 'date',
      'label'        => _x( 'Additional driver 2 — Date of birth', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'birth',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],
    'additional_driver_2_driving_license_number' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 2 — License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],
    'additional_driver_2_driving_license_date' => [
      'type'         => 'date',
      'label'        => _x( 'Additional driver 2 — License issue date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'license',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],
    'additional_driver_2_driving_license_country' => [
      'type'         => 'text',
      'label'        => _x( 'Additional driver 2 — License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 50,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],
    'additional_driver_2_driving_license_expiration_date' => [
      'type'         => 'date',
      'label'        => _x( 'Additional driver 2 — License expiry', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => 'dd/mm/yyyy',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 10,
      'has_intl_tel' => false,
      'datepicker'   => 'license',
      'special'      => '',
      'group'        => 'additional_driver_2',
    ],

    // ── Engine-managed special fields ───────────────────────────────────────
    // These are only shown in the builder if the Mybooking account has them enabled.
    // Visibility at runtime is controlled entirely by the JS engine (show/hide).
    'slot_time_from' => [
      'type'         => 'select',
      'label'        => _x( 'Delivery slot', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => '',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 0,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => 'delivery_slot',
      'group'        => 'engine',
    ],
    'with_optional_external_driver' => [
      'type'         => 'select',
      'label'        => _x( 'Skipper / External driver', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'  => '',
      'required'     => false,
      'removable'    => true,
      'maxlength'    => 0,
      'has_intl_tel' => false,
      'datepicker'   => '',
      'special'      => 'external_driver',
      'group'        => 'engine',
    ],

    ];
    return $fields;
  }
}
