<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * MYBOOKING CHECKOUT FORM — Field Catalog
 *
 * Defines all fields that can be placed in the checkout form builder.
 *
 * Each entry:
 *   type                 : input type (text|email|tel|textarea|select|date|number|time)
 *   label                : default translatable label
 *   placeholder          : default translatable placeholder (empty string if none)
 *   required             : whether the field is required by default
 *   removable            : false = field locked; cannot be removed by the admin
 *   maxlength            : max input length (0 = no limit)
 *   has_intl_tel         : true = Engine will init intlTelInput on this field
 *   date_direction       : 'past'|'future' — direction for date composite controls (type=date only)
 *   special              : 'delivery_slot'|'external_driver'|'' — Engine-managed block
 *   group                : logical grouping for the admin panel UI
 *   engine_targets       : engines that consume this field at runtime (['renting','activities','transfers'])
 *   business_lines       : renting business lines where field is relevant (['common','vehicle','boat','accommodation','activities','transfers'])
 *   runtime_name         : runtime HTML name override; empty = use field key
 *   runtime_name_by_engine : per-engine runtime name overrides, e.g. ['transfers' => 'customer_address_street']
 *   option_source        : Engine-managed option population key, e.g. 'engine_nationalities'
 *   runtime_guard        : feature flag/condition controlling field visibility at runtime
 *
 * Runtime-name resolution order:
 *   1. runtime_name_by_engine[current_engine]
 *   2. runtime_name
 *   3. field key
 *
 * Catalog size: 104 total — 102 ordinary + 2 Engine specials (slot_time_from, with_optional_external_driver)
 * Dates: 16 total — 10 past / 6 future
 *
 * Country/nationality selects (type=select): Engine populates translated options.
 * Date composites (type=date): P4 emits .js-date-select-control wrapper with day/month/year selects.
 * Phone fields (type=tel, has_intl_tel=true): Engine applies intlTelInput.
 */


/**
 * Returns the checkout field catalog with labels translated to the current admin locale.
 * Uses static memoization — first call happens at admin page render, after text domain load.
 */
if ( ! function_exists( 'mybooking_checkout_form_fields' ) ) {
  function mybooking_checkout_form_fields() {
    static $fields = null;
    if ( $fields !== null ) {
      return $fields;
    }
    $fields = [

    // ── Customer (core — locked) ────────────────────────────────────────────
    'customer_name' => [
      'type'                  => 'text',
      'label'                 => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => false,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer',
      'engine_targets'        => [ 'renting', 'activities', 'transfers' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'customer_surname' => [
      'type'                  => 'text',
      'label'                 => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => false,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer',
      'engine_targets'        => [ 'renting', 'activities', 'transfers' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'customer_email' => [
      'type'                  => 'email',
      'label'                 => _x( 'E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => false,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer',
      'engine_targets'        => [ 'renting', 'activities', 'transfers' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'confirm_customer_email' => [
      'type'                  => 'email',
      'label'                 => _x( 'Confirm E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Confirm E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => false,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer',
      'engine_targets'        => [ 'renting', 'activities', 'transfers' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'customer_phone' => [
      'type'                  => 'tel',
      'label'                 => _x( 'Phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => false,
      'maxlength'             => 15,
      'has_intl_tel'          => true,
      'special'               => '',
      'group'                 => 'customer',
      'engine_targets'        => [ 'renting', 'activities', 'transfers' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Customer (removable) ────────────────────────────────────────────────
    'customer_mobile_phone' => [
      'type'                  => 'tel',
      'label'                 => _x( 'Alternative phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Alternative phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 15,
      'has_intl_tel'          => true,
      'special'               => '',
      'group'                 => 'customer',
      'engine_targets'        => [ 'renting', 'activities', 'transfers' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'comments' => [
      'type'                  => 'textarea',
      'label'                 => _x( 'Comments', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Comments', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer',
      'engine_targets'        => [ 'renting', 'activities', 'transfers' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Address ─────────────────────────────────────────────────────────────
    'street' => [
      'type'                  => 'text',
      'label'                 => _x( 'Street', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Street', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 60,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'address',
      'engine_targets'        => [ 'renting', 'transfers' ],
      'business_lines'        => [ 'common', 'accommodation', 'vehicle', 'boat', 'transfers' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [ 'transfers' => 'customer_address_street' ],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'accommodation', 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'complement' => [
      'type'                  => 'text',
      'label'                 => _x( 'Complement', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Complement', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 20,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'accommodation', 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'city' => [
      'type'                  => 'text',
      'label'                 => _x( 'City', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'City', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 60,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'address',
      'engine_targets'        => [ 'renting', 'transfers' ],
      'business_lines'        => [ 'common', 'accommodation', 'vehicle', 'boat', 'transfers' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [ 'transfers' => 'customer_address_city' ],
      'option_source'         => '',
      'runtime_guard'         => '',
      'atomic_group'          => 'customer_address_geo',
    ],
    'state' => [
      'type'                  => 'text',
      'label'                 => _x( 'State', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'State', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 60,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'address',
      'engine_targets'        => [ 'renting', 'transfers' ],
      'business_lines'        => [ 'common', 'accommodation', 'vehicle', 'boat', 'transfers' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [ 'transfers' => 'customer_address_state' ],
      'option_source'         => '',
      'runtime_guard'         => '',
      'atomic_group'          => 'customer_address_geo',
    ],
    'country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'address',
      'engine_targets'        => [ 'renting', 'transfers' ],
      'business_lines'        => [ 'common', 'accommodation', 'vehicle', 'boat', 'transfers' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [ 'transfers' => 'customer_address_country' ],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
      'atomic_group'          => 'customer_address_geo',
    ],
    'zip' => [
      'type'                  => 'text',
      'label'                 => _x( 'Postal code', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Postal code', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'address',
      'engine_targets'        => [ 'renting', 'transfers' ],
      'business_lines'        => [ 'common', 'accommodation', 'vehicle', 'boat', 'transfers' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [ 'transfers' => 'customer_address_zip' ],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Flight (arrival) ────────────────────────────────────────────────────
    'fligth_airport_origin' => [
      'type'                  => 'text',
      'label'                 => _x( 'Origin airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Origin airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 100,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_arrival',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'flight_company' => [
      'type'                  => 'text',
      'label'                 => _x( 'Airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 80,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_arrival',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'flight_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_arrival',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'flight_time' => [
      'type'                  => 'text',
      'label'                 => _x( 'Expected arrival time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'HH:MM',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 5,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_arrival',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Flight (departure) ──────────────────────────────────────────────────
    'fligth_airport_destination' => [
      'type'                  => 'text',
      'label'                 => _x( 'Destination airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Destination airport', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 100,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_departure',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'flight_company_departure' => [
      'type'                  => 'text',
      'label'                 => _x( 'Return airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Return airline', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 80,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_departure',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'flight_number_departure' => [
      'type'                  => 'text',
      'label'                 => _x( 'Return flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Return flight number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_departure',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'flight_time_departura' => [
      'type'                  => 'text',
      'label'                 => _x( 'Expected return time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'HH:MM',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 5,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'flight_departure',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Driver (base) ───────────────────────────────────────────────────────
    'driver_name' => [
      'type'                  => 'text',
      'label'                 => _x( 'Driver name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Driver name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_surname' => [
      'type'                  => 'text',
      'label'                 => _x( 'Driver surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Driver surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_document_id' => [
      'type'                  => 'text',
      'label'                 => _x( 'Driver ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Driver ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_date_of_birth' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of birth', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_driving_license_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_driving_license_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'License issue date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_driving_license_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
    ],
    'driver_driving_license_expiration_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'License expiry date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'future',
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Additional driver 1 ─────────────────────────────────────────────────
    'additional_driver_1_name' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 1 — Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_surname' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 1 — Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_document_id' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 1 — ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_date_of_birth' => [
      'type'                  => 'date',
      'label'                 => _x( 'Additional driver 1 — Date of birth', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_driving_license_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 1 — License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_driving_license_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Additional driver 1 — License issue date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_driving_license_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Additional driver 1 — License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_driving_license_expiration_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Additional driver 1 — License expiry', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'future',
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Additional driver 2 ─────────────────────────────────────────────────
    'additional_driver_2_name' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 2 — Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_surname' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 2 — Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Surname', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_document_id' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 2 — ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'ID document', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_date_of_birth' => [
      'type'                  => 'date',
      'label'                 => _x( 'Additional driver 2 — Date of birth', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_driving_license_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Additional driver 2 — License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_driving_license_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Additional driver 2 — License issue date', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_driving_license_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Additional driver 2 — License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_driving_license_expiration_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Additional driver 2 — License expiry', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'date_direction'        => 'future',
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Engine-managed special fields ───────────────────────────────────────
    'slot_time_from' => [
      'type'                  => 'select',
      'label'                 => _x( 'Delivery slot', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => '',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => 'delivery_slot',
      'group'                 => 'engine',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'with_optional_external_driver' => [
      'type'                  => 'select',
      'label'                 => _x( 'Skipper / External driver', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => '',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => 'external_driver',
      'group'                 => 'engine',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => '',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Customer classification ─────────────────────────────────────────────
    'customer_type' => [
      'type'                  => 'select',
      'label'                 => _x( 'Customer type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Customer type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer_classification',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_type',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'static_customer_type',
      'runtime_guard'         => '',
    ],
    'customer_classifier_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'Customer classifier', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Customer classifier', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer_classification',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_classifier_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_customer_classifier',
      'runtime_guard'         => 'useCustomerClassifier',
    ],

    // ── Customer identity ───────────────────────────────────────────────────
    'customer_date_of_birth' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of birth', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'customer_identity',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_date_of_birth',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'customer_nacionality' => [
      'type'                  => 'select',
      'label'                 => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer_identity',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_nacionality',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_nationalities',
      'runtime_guard'         => '',
    ],
    'customer_document_id_type_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer_identity',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_document_id_type_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_document_types',
      'runtime_guard'         => '',
    ],
    'customer_document_id' => [
      'type'                  => 'text',
      'label'                 => _x( 'ID card/passport number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'ID card/passport number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer_identity',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_document_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'customer_origin_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'customer_identity',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_origin_country',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
    ],

    // ── Company details ─────────────────────────────────────────────────────
    'customer_company_name' => [
      'type'                  => 'text',
      'label'                 => _x( 'Company name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Company name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'company_details',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_company_name',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'customer_company_contact_name' => [
      'type'                  => 'text',
      'label'                 => _x( 'Company contact name', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Company contact name', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'company_details',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_company_contact_name',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'customer_company_document_id' => [
      'type'                  => 'text',
      'label'                 => _x( 'Company VAT Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Company VAT Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 40,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'company_details',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'common', 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'customer_company_document_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Accommodation details ───────────────────────────────────────────────
    'number_of_adults' => [
      'type'                  => 'number',
      'label'                 => _x( 'Number of adults', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Number of adults', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'accommodation_details',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'accommodation', 'vehicle' ],
      'runtime_name'          => 'number_of_adults',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'destination_accommodation' => [
      'type'                  => 'textarea',
      'label'                 => _x( 'Destination accommodation', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Destination accommodation', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'accommodation_details',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'accommodation' ],
      'runtime_name'          => 'destination_accommodation',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Driver details (extended) ───────────────────────────────────────────
    'driver_nacionality' => [
      'type'                  => 'select',
      'label'                 => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => 'driver_nacionality',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_nationalities',
      'runtime_guard'         => '',
    ],
    'driver_email' => [
      'type'                  => 'email',
      'label'                 => _x( 'E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'E-mail', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => 'driver_email',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_phone' => [
      'type'                  => 'tel',
      'label'                 => _x( 'Phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Phone number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 15,
      'has_intl_tel'          => true,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => 'driver_phone',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Driver identity ─────────────────────────────────────────────────────
    'driver_document_id_type_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => 'driver_document_id_type_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_document_types',
      'runtime_guard'         => '',
    ],
    'driver_origin_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => 'driver_origin_country',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
    ],
    'driver_document_id_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of Issue', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => 'driver_document_id_date',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_document_id_expiration_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of expiry', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'date_direction'        => 'future',
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat' ],
      'runtime_name'          => 'driver_document_id_expiration_date',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Driver license (vehicle-specific) ───────────────────────────────────
    'driver_driving_license_type_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'License type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'driver_driving_license_type_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_license_types',
      'runtime_guard'         => '',
    ],

    // ── Driver address ──────────────────────────────────────────────────────
    'driver_address_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver_address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'driver_address[country]',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
      'atomic_group'          => 'driver_address_geo',
    ],
    'driver_address_state' => [
      'type'                  => 'text',
      'label'                 => _x( 'State', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'State', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver_address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'driver_address[state]',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
      'atomic_group'          => 'driver_address_geo',
    ],
    'driver_address_city' => [
      'type'                  => 'text',
      'label'                 => _x( 'City', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'City', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver_address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'driver_address[city]',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
      'atomic_group'          => 'driver_address_geo',
    ],
    'driver_address_zip' => [
      'type'                  => 'text',
      'label'                 => _x( 'Postal code', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Postal code', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver_address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'driver_address[zip]',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_address_street' => [
      'type'                  => 'text',
      'label'                 => _x( 'Street', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Street', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 60,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver_address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'driver_address[street]',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_address_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 10,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver_address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'driver_address[number]',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'driver_address_complement' => [
      'type'                  => 'text',
      'label'                 => _x( 'Complement', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Complement', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 20,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver_address',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle', 'boat', 'accommodation' ],
      'runtime_name'          => 'driver_address[complement]',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Skipper / boat navigation license ───────────────────────────────────
    'driver_driving_license_type' => [
      'type'                  => 'text',
      'label'                 => _x( 'Navigation license type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Navigation license type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'driver',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'boat' ],
      'runtime_name'          => 'driver_driving_license_type',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],

    // ── Additional driver 1 (extended) ──────────────────────────────────────
    'additional_driver_1_nacionality' => [
      'type'                  => 'select',
      'label'                 => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_1_nacionality',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_nationalities',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_document_id_type_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_1_document_id_type_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_document_types',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_origin_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_1_origin_country',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_document_id_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of Issue', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_1_document_id_date',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_document_id_expiration_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of expiry', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'date_direction'        => 'future',
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_1_document_id_expiration_date',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_1_driving_license_type_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'License type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_1',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_1_driving_license_type_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_license_types',
      'runtime_guard'         => '',
    ],

    // ── Additional driver 2 (extended) ──────────────────────────────────────
    'additional_driver_2_nacionality' => [
      'type'                  => 'select',
      'label'                 => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Nationality', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_2_nacionality',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_nationalities',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_document_id_type_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Document type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_2_document_id_type_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_document_types',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_origin_country' => [
      'type'                  => 'select',
      'label'                 => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Expedition country', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_2_origin_country',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_countries',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_document_id_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of Issue', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'date_direction'        => 'past',
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_2_document_id_date',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_document_id_expiration_date' => [
      'type'                  => 'date',
      'label'                 => _x( 'Date of expiry', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'dd/mm/yyyy',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'date_direction'        => 'future',
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_2_document_id_expiration_date',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => '',
    ],
    'additional_driver_2_driving_license_type_id' => [
      'type'                  => 'select',
      'label'                 => _x( 'License type', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'License type', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'additional_driver_2',
      'engine_targets'        => [ 'renting' ],
      'business_lines'        => [ 'vehicle' ],
      'runtime_name'          => 'additional_driver_2_driving_license_type_id',
      'runtime_name_by_engine'=> [],
      'option_source'         => 'engine_license_types',
      'runtime_guard'         => '',
    ],

    // ── Activity customer vehicle ────────────────────────────────────────────
    'customer_stock_brand' => [
      'type'                  => 'text',
      'label'                 => _x( 'Brand', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Brand', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => true,
      'maxlength'             => 100,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'activity_vehicle',
      'engine_targets'        => [ 'activities' ],
      'business_lines'        => [ 'activities' ],
      'runtime_name'          => 'customer_stock_brand',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'activityCustomerVehicle',
    ],
    'customer_stock_model' => [
      'type'                  => 'text',
      'label'                 => _x( 'Model', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Model', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => true,
      'maxlength'             => 100,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'activity_vehicle',
      'engine_targets'        => [ 'activities' ],
      'business_lines'        => [ 'activities' ],
      'runtime_name'          => 'customer_stock_model',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'activityCustomerVehicle',
    ],
    'customer_stock_plate' => [
      'type'                  => 'text',
      'label'                 => _x( 'Stock plate', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Stock plate', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => true,
      'removable'             => true,
      'maxlength'             => 100,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'activity_vehicle',
      'engine_targets'        => [ 'activities' ],
      'business_lines'        => [ 'activities' ],
      'runtime_name'          => 'customer_stock_plate',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'activityCustomerVehicle',
    ],
    'customer_stock_color' => [
      'type'                  => 'text',
      'label'                 => _x( 'Color', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Color', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 100,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'activity_vehicle',
      'engine_targets'        => [ 'activities' ],
      'business_lines'        => [ 'activities' ],
      'runtime_name'          => 'customer_stock_color',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'activityCustomerVehicle',
    ],

    // ── Transfer outbound details ────────────────────────────────────────────
    'detailed_origin_address' => [
      'type'                  => 'text',
      'label'                 => _x( 'Pickup address', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Pickup address', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_outbound',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_origin_address',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_origin_flight_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_outbound',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_origin_flight_number',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_origin_flight_estimated_time' => [
      'type'                  => 'time',
      'label'                 => _x( 'Flight or vessel estimated time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'HH:MM',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_outbound',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_origin_flight_estimated_time',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_destination_address' => [
      'type'                  => 'text',
      'label'                 => _x( 'Dropoff address', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Dropoff address', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_outbound',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_destination_address',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_destination_flight_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_outbound',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_destination_flight_number',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_destination_flight_estimated_time' => [
      'type'                  => 'time',
      'label'                 => _x( 'Flight or vessel estimated time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'HH:MM',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_outbound',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_destination_flight_estimated_time',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],

    // ── Transfer return details ──────────────────────────────────────────────
    'detailed_return_origin_address' => [
      'type'                  => 'text',
      'label'                 => _x( 'Return pickup address', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Return pickup address', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_return',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_return_origin_address',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_return_origin_flight_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_return',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_return_origin_flight_number',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_return_origin_flight_estimated_time' => [
      'type'                  => 'time',
      'label'                 => _x( 'Flight or vessel estimated time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'HH:MM',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_return',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_return_origin_flight_estimated_time',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_return_destination_address' => [
      'type'                  => 'text',
      'label'                 => _x( 'Return dropoff address', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Return dropoff address', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_return',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_return_destination_address',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_return_destination_flight_number' => [
      'type'                  => 'text',
      'label'                 => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => _x( 'Flight or vessel number', 'renting_complete', 'mybooking-reservation-engine' ),
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 50,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_return',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_return_destination_flight_number',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],
    'detailed_return_destination_flight_estimated_time' => [
      'type'                  => 'time',
      'label'                 => _x( 'Flight or vessel estimated time', 'renting_complete', 'mybooking-reservation-engine' ),
      'placeholder'           => 'HH:MM',
      'required'              => false,
      'removable'             => true,
      'maxlength'             => 0,
      'has_intl_tel'          => false,
      'special'               => '',
      'group'                 => 'transfer_return',
      'engine_targets'        => [ 'transfers' ],
      'business_lines'        => [ 'transfers' ],
      'runtime_name'          => 'detailed_return_destination_flight_estimated_time',
      'runtime_name_by_engine'=> [],
      'option_source'         => '',
      'runtime_guard'         => 'transfer_origin_destination_detailed_info_mode',
    ],

    ];
    return $fields;
  }
}
